"""add_column_metadata_and_tags

Revision ID: adfde5826b0e
Revises: 
Create Date: 2026-04-19 17:45:46.739086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfde5826b0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dd_columns')
    op.drop_table('dd_joins')
    op.drop_table('dd_tables')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dd_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dd_tables_pkey')),
    sa.UniqueConstraint('schema_name', 'table_name', name=op.f('dd_tables_schema_name_table_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dd_joins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_schema', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('from_table', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('from_column', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('to_schema', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('to_table', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('to_column', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('join_type', sa.VARCHAR(length=20), server_default=sa.text("'INNER'::character varying"), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dd_joins_pkey'))
    )
    op.create_table('dd_columns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_primary_key', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_foreign_key', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('references_table', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('references_column', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dd_columns_pkey')),
    sa.UniqueConstraint('schema_name', 'table_name', 'column_name', name=op.f('dd_columns_schema_name_table_name_column_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
